catering/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path("", views.index, name = 'index'),
    path("contact_form", views.contact_form, name = 'contact_form'),
    path('products', views.products, name = 'products')
]

main/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(default = None, max_length = 300)
    def __str__(self):
        return self.name
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete = models.DO_NOTHING,
    blank= True, null = True)
    name = models.CharField(default = None, max_length = 300)
    price = models.IntegerField(default = None, blank = True, null = True)
    imgsrc = models.ImageField(upload_to="static/images/products", default = None, blank = True)
    def __str__(self):
        return self.name


def delall():
    c =  Category.objects.all()
    p = Product.objects.all()
    p.delete()
    c.delete()
    print('deleted all')

main/views.py
from django.shortcuts import render
from .models import * 
from django.http import JsonResponse, HttpResponse
import urllib
from django.core.files.storage import default_storage
from catering.settings import * 
import json
from django.template.loader import render_to_string
import os

from django.core.mail import send_mail
from django.conf import settings


# Create your views here.

def index(request):
    template = "main/index.html"
    products = Product.objects.all()[:10]
    somelist = [1,2,3,4]
    context = {
        'products': products,
        'somelist': somelist,
    }
    return render(request, template, context)

def products(request):
    template = "main/products.html"
    products = Product.objects.all()
    somelist = [1,2,3,4]
    context = {
        'somelist': somelist,
        'products': products,
    }
    return render(request, template, context)

def contact_form(request):
    is_sended = True
    phone = request.GET['phone']

    try:
        send_mail(
            'Заявка на обратный звонок c сайта кейтеринга',
            'Номер телефона: {} '.format(phone),
            settings.EMAIL_HOST_USER,
            [
            'worlddelete0@mail.ru', 
            ],
            )
    except:
        pass

    return JsonResponse({
        'is_sended': is_sended,
    })

templates/main/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Кейтеринг в Крыму</title>
</head>
<body>

{% include './includes_css.html' %}
{% include './includes_js.html' %}



{% block header %}
    <div class="main__header__block__wrapper">

    <div id="scroll_to_top"></div>

    <div class="main__header__block">
        {% include './blocks/header.html' %}
    </div>
{% endblock header %}


{% block content %}
{% endblock content %}

{% include './blocks/popup_form.html' %}

</body>

<script>
    var sticky = new Waypoint.Sticky({
    element: $('.main__header__block'), // Add in your CSS selector sticky target
    // direction: 'down right',
  })
  
$(".callme_link").click(function() {
        current_form = $("#main__popup")
        showModal(current_form)
    })

    $(".pform__wrap__close").click(function() {
    closeModal()
})
    $(".pform__wrap__wrapper").click(function() {
    closeModal()
})


function showModal(item) {
    $(item).addClass("show")
    $(".pform__wrap__wrapper").addClass("show")
}
function closeModal() {
    $(".pform__wrap").removeClass("show")
    $(".pform__wrap__wrapper").removeClass("show")
}

$(".pform__wrap__close").click(function() {
    closeModal()
})
$(".pform__wrap__wrapper").click(function() {
    closeModal()
})
</script>

</html>

templates/main/blocks/about_us.html
<div id="about_us_anchor"></div>
<div class="about_us_container">
    <div class="about_us_title">
        О Нас
    </div>
    <div class="about_us_description">
        Наша кейтеринговая компания представляет услуги для своих уважаемых клиентов на высоком профессиональном уровне. 
        Наши сотрудники знают, как организовать фуршеты, банкеты и иные пышные мероприятия так, чтобы это запомнилось всем гостям надолго. 
        Так, если Вам необходимо провести корпоратив, деловую встречу или пикник на природе, выбирайте нашу сеть гастрономического питания. 
        Интересует кейтеринг в Крым? Это дело под силу нашим профессионалам, способным справиться с мероприятием любой сложности, ведь мы любим свое дело и всех своих клиентов.
    </div>
</div>

templates/main/blocks/action_call.html
<div class="action_call_wrapper">
    <div class="action_call_title">
        <span>
            Оставьте заявку, и мы обсудим детали вашего события 
        </span>
    </div>
    <div class="action_call_button">
        <span class="custom-btn btn-14 style_2 callme_link">
            Оставить заявку
        </span>
    </div>
</div>

templates/main/blocks/adv_container.html
<div class="adv__wrapper">

    <div class="nice_title center green middle">
        <span>
        Наши преимущества
        </span>
    </div>

    <div class="adv__main">

        <div class="adv__main__item">
            <div class="adv__main__item__title">
            Высококвалифицированный персонал в компании, постоянные тренинги и стажировки
            </div>
            <div class="adv__main__item__counter">
                01
            </div>
        </div>

        <div class="adv__main__item">
            <div class="adv__main__item__title">
            Возможность создания меню исходя из концепции мероприятия с привлечением бренд-шефа
            </div>
            <div class="adv__main__item__counter">
                02
            </div>
        </div>

        <div class="adv__main__item">
            <div class="adv__main__item__title">
            Обладание рядом премий и наград в индустрии выездного обслуживания
            </div>
            <div class="adv__main__item__counter">
                03
            </div>
        </div>
        <div class="adv__main__item">
            <div class="adv__main__item__title">
            Мы открыты и ничего не скрываем от своих клиентов. 
            Хотите контролировать процесс подготовки вашего мероприятия и убедиться в мастерстве наших поваров? Мы дадим вам такую возможность!
            </div>
            <div class="adv__main__item__counter">
                04
            </div>
        </div>
        <div class="adv__main__item">
            <div class="adv__main__item__title">
            Мы отвечаем за уровень предоставляемых услуг. В этом нам помогает собственная система контроля качества, работающая на всех уровнях организации кейтеринга.
            </div>
            <div class="adv__main__item__counter">
                05
            </div>
        </div>
        <div class="adv__main__item">
            <div class="adv__main__item__title">
            Мы предоставляем комплекс услуг по организации питания на различных мероприятиях. 
            Помимо приготовления и доставки праздничных блюд мы предлагаем аренду мебели и посуды на ресторанный кейтеринг, возможность заказа обслуживающего персонала, оформления для мероприятий
            </div>
            <div class="adv__main__item__counter">
                06
            </div>
        </div>

    </div>
</div>

templates/main/blocks/contacts_container.html
<div class="contacts_container_wrapper__main">
<div class="contacts_container_wrapper">
    <div class="contacts_content1">
        <div class="contacts__title">
            Наши контакты
        </div>
        <div class="contact__item">
            <div class="contact__item__icon">
                <i class="fa fa-route"></i>
            </div>
            <div class="contact__item__text">
                Симферополь, ул. Киевская, д. 126
            </div>
        </div>
        <div class="contact__item">
            <div class="contact__item__icon">
                <i class="fa fa-phone-alt"></i>
            </div>
            <div class="contact__item__text">
                +7 (978)-xxx-xx-xx
            </div>
        </div>
    </div>
    <div class="contacts_content2">
        <div class="contacts__title2">
            Сделем ваше событие незабываемым!
        </div>
        <div class="contact2_button">
            <span class="custom-btn btn-14 style_2 callme_link">
                Узнать как
            </span>
        </div>
    </div>
</div>
</div>

templates/main/blocks/h_first.html
<div class="main__header__first">
    <div class="main__header__first__container">
        <div class="header__first__container__item">
            О нас
        </div>
        <div class="header__first__container__item">
            Доставка
        </div>
        <div class="header__first__container__item">
            Оплата
        </div>
    </div>
</div>

templates/main/blocks/header.html
<!-- {% include './h_first.html' %} -->
{% load static %}


<div class="main__header__second__mobile__logo">
    <a class="header__second__logo mobile__logo"
    href="{% url 'main:index' %}">
        <img src="{% static 'images/logo1.png' %}" alt="">
    </a>

    <!-- <div class="header__second__search">
        <form
        class="header__second__search__form">
            {% csrf_token %}
            <input type="text" class="input_search"
            name="search_input"
            placeholder="Искать">
            <button class="input_submit">
                <i class="gg-search"></i>
            </button>
        </form>
    </div> -->

</div>

<div class="main__header__second">
    <a class="header__second__logo logo__big"
    href="{% url 'main:index' %}">
        <img src="{% static 'images/logo1.png' %}" alt="">
    </a>

    <div class="header__second__catalog">
        <div class="header__second__catalog__items">
            <a href="{% url 'main:index' %}">
                Главная
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a href="{% url 'main:index' %}#services_anchor">
                Услуги
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a
            href="{% url 'main:products' %}">
                Меню
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a
            href="{% url 'main:index' %}#projects_anchor">
                Проекты
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a
            href="{% url 'main:index' %}#about_us_anchor">
                О Нас
            </a>
        </div>
    </div>

    <div class="main__header__phone">
        <!-- <div class="main__header__phone__main">
            <i class="fa fa-phone-alt"></i>
            <div class="main__header__phone__main__text">
                <a href="tel:+79781161415">
                    +7 (978) 116-14-15
                </a>
            </div>
        </div> -->
        <div class="main__header__phone__callme">
            <span class="main__header__phone__callme callme_link">
                Заказать звонок
            </span>
        </div>
    </div>

    <div class="header__second__catalog__mobile__wrapper">
    <span class="header__second__catalog__mobile">
        <div class="header__second__catalog__mobile__items">
            <i class="gg-menu-left-alt"></i>
            <span href="">
                Меню
            </span>
        </div>
    </span>
    </div>    

    <div class="main__header__phone__mobile">
        <!-- <div class="main__header__phone__main">
            <i class="fa fa-phone-alt"></i>
            <div class="main__header__phone__main__text">
                <a href="tel:+79781161415">
                    +7 (978) 116-14-15
                </a>
            </div>
        </div> -->
        <div class="main__header__phone__callme">
            <span class="main__header__phone__callme callme_link">
                Заказать звонок
            </span>
        </div>
    </div>


    <div class="header__second__icons">



        <!-- <a class="header__second__icons__item account__big">
            <svg height="24" viewBox="0 0 20 20" width="24"><path d="M16.984 14.506V17H3.016v-2.494C4.47 11.794 6.797 10.438 10 10.438s5.531 1.356 6.984 4.068zM10 11.938c-2.528 0-4.295.958-5.484 2.961v.6h10.968v-.6c-1.19-2.003-2.956-2.961-5.484-2.961zm3.686-6.384a3.686 3.686 0 11-7.372 0 3.686 3.686 0 017.372 0zm-1.5 0a2.186 2.186 0 10-4.372 0 2.186 2.186 0 004.372 0z"></path></svg>
        </a> -->

    </div>
</div>


<div class="header__popup__mobile">
    <div class="header__popup__mobile__menu">
        <a href="{% url 'main:index' %}"
            class="mobile__nav">
                Главная
            </a>
            <a href="{% url 'main:index' %}#services_anchor"
            class="mobile__nav">
                Услуги
            </a>
            <a
            href="{% url 'main:products' %}"
            class="mobile__nav">
                Меню
            </a>
            <a
            href="{% url 'main:index' %}#projects_anchor"
            class="mobile__nav">
                Проекты
            </a>
            <a
            href="{% url 'main:index' %}#about_us_anchor"
            class="mobile__nav">
                О Нас
            </a>
    </div>
</div>
<div class="header__popub__mobile__close">
    <i class="fa fa-close"></i>
</div>
<div class="header__popup__mobile__wrapper">

</div>



<script>
    // $(".header__second__catalog").click(function() {
    //     $(".catalog_open").toggleClass("hide")
    //     $(".catalog_close").toggleClass("show")
    //     $(".header__second__catalog").toggleClass("opened")
    //     $(".header__second__catalog__items").toggleClass("opened")
    // })
    $(".header__second__catalog__mobile").click(function() {
        openMobileMenu()
    })
    $(".header__popub__mobile__close").click(function() {
        closeMobileMenu()
    })
    $(".mobile__nav").click(function() {
        closeMobileMenu()
    })


    function openMobileMenu() {
            $(".header__popup__mobile").addClass("show")
            $(".header__popub__mobile__close").addClass("show")
            $("body").addClass("hidden")
        }
    function closeMobileMenu() {
            $(".header__popup__mobile").removeClass("show")
            $(".header__popub__mobile__close").removeClass("show")
            $("body").removeClass("hidden")
        }
</script>

templates/main/blocks/intro_container.html
{% load static %}
<div class="case-main dark case-main-top">
    <div class="case-main-text">
        <h3 class="case-main__title aos-init aos-animate" data-aos="fade-down">Кейтеринг в Крыму</h3>
        <p class="case-main__desc aos-init aos-animate" data-aos="fade-down" data-aos-delay="150">
            Организация событийного и корпоративного кейтеринга в Крыму. Опыт проведения мероприятий до 3000 человек. 
        </p>
    </div>
    <div class="case-main-img-wrapper">
        <noscript><img data-aos-anchor=".case-main__title" data-aos-duration="700" data-aos="fade-left" data-aos-delay="250" src="{% static 'images/main_banner.png' %}" alt=""></noscript>
        <img class="aos-init lazyloaded aos-animate" data-aos-anchor=".case-main__title" data-aos-duration="700" data-aos="fade-left" data-aos-delay="250" src="{% static 'images/main_banner.png' %}" data-src="{% static 'images/main_banner.png' %}" alt="">
    </div>
</div>


<script>
    $.fn.extend({
  anican: function(i) {
    
    //defaults
    let config = {
      background: "#111",
      size: 20,
      speed: 0.5,
      zindex: 0,
      max: 50,
      colors: [
        "#2980B9",
        "#F14155",
        "#27AE60",
        "#FBA026"
      ]
    };
    
    try{
      //check defaults
      for (let key in config) {
        if(!i[key]){
          i[key] = config[key];
        }
      }
      
      //build frame
      $(this).prepend(
        $("<canvas />")
          .addClass("anican")
          .css({
            "display": "transparent",
            "background": "none",
            "position": "fixed",
            "left": 0,
            "top": 0,
            "overflow": "hidden",
            "z-index": i.zindex,
            "pointer-events": "none",
          })
      );
    } catch(e){
      if(e){ return console.log(e)}
    }
    

    let canvas = $(".anican")[0],
    context = canvas.getContext("2d"),
    Dots = [],
    colors = i.colors,
    maximum = i.max;

    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    function Initialize() {
      GenerateDots();
      Update();
    }

    function Dot() {
       try{
        this.active = true;
        this.diameter = Math.random() * i.size;
        this.x = Math.round(Math.random() * canvas.width);
        this.y = Math.round(Math.random() * canvas.height);
        this.velocity = {
          x: (Math.random() < 0.5 ? -1 : 1) * Math.random() * i.speed,
          y: (Math.random() < 0.5 ? -1 : 1) * Math.random() * i.speed
        };
        this.alpha = 0.1;
        this.hex = colors[Math.round(Math.random() * 3)];
        this.color = HexToRGBA(this.hex, this.alpha);
      } catch(e){
        if (e) {return console.log(e)}
      }
    }

    Dot.prototype = {
      Update: function() {
        try{
          if (this.alpha < 0.8) {
            this.alpha += 0.01;
            this.color = HexToRGBA(this.hex, this.alpha);
          }

          this.x += this.velocity.x;
          this.y += this.velocity.y;

          if (
            this.x > canvas.width + 5 ||
            this.x < 0 - 5 ||
            this.y > canvas.height + 5 ||
            this.y < 0 - 5
          ) {
            this.active = false;
          }
        } catch(e){
          if (e) {return console.log(e)}
        }
      },
      Draw: function() {
        try{
          context.fillStyle = this.color;
          context.beginPath();
          context.arc(this.x, this.y, this.diameter, 0, Math.PI * 2, false);
          context.fill();
        } catch(e){
          if (e) {return console.log(e)}
        }
      }
    };

    function Update() {
      GenerateDots();
      Dots.forEach(function(Dot) {
        Dot.Update();
      });
      Dots = Dots.filter(function(Dot) {
        return Dot.active;
      });
      Render();
      requestAnimationFrame(Update);
    }

    function Render() {
      try{
        context.clearRect(0, 0, canvas.width, canvas.height);
        Dots.forEach(function(Dot) {
          Dot.Draw();
        });
      } catch(e){
        if(e) { return console.log(e)}
      }
    }

    function GenerateDots() {
      try {
        if (Dots.length < maximum) {
          for (var i = Dots.length; i < maximum; i++) {
            Dots.push(new Dot());
          }
        }
        return false;
      } catch (e) {
        if(e){ return console.log(e)}
      }
    }

    function HexToRGBA(hex, alpha) {
      try{
        let red = parseInt(TrimHex(hex).substring(0, 2), 16),
        green = parseInt(TrimHex(hex).substring(2, 4), 16),
        blue = parseInt(TrimHex(hex).substring(4, 6), 16);
        return "rgba(" + red + ", " + green + ", " + blue + ", " + alpha + ")";
      } catch(e){
        if(e){return console.log(e)}
      }
    }

    function TrimHex(hex) {
      try {
        let res = hex.charAt(0) === "#" ? hex.substring(1, 7) : h;
        return res;
      } catch (e) {
        if(e){return console.log(e)}
      }
    }

    $(window).on("resize", function() {
        Dots = [];
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
      });
    
    return Initialize();
  }
});

//call plugin
$(".case-main-top").anican({
  //optional defaults
//   background: none,
  colors: [
    "#2980B9",
    "#F14155",
    "#27AE60",
    "#FBA026"
   ],
  zindex: 1,
  max: 50,
  size: 2,
  speed: 0.6,
});

</script>

templates/main/blocks/menu_block.html
{% load static %}

<div class="menu_block_wrapper wrap_pad15">
    <div class="nice_title center orange">
        <span>
        Меню
        </span>
    </div>

    <div class="menu__container">
        <img class="menu__container__img"
        src="{% static 'images/menu_container_banner.png' %}" alt="">
        <div class="menu__blocks">
            <div class="menu__blocks__sub owl-carousel owl-theme">
            {% for product in products  %}
            {% include './menu_single.html' %}
            {% endfor %}
            </div>
            <div class="menu__link">
                <a class="custom-btn btn-14"
                href="{% url 'main:products' %}">
                    Смотреть все
                </a>
            </div>
        </div>
        

    </div>

</div>

templates/main/blocks/menu_single.html
{% load static %}
{% load main_extras %}
<div class="menu__block">
    <div class="menu__block__image">
    {% modify_imgsrc product.imgsrc as imgsrc %}
        <img src="{{ imgsrc }}" alt="">
    </div>
    <div class="info__block">
    <div class="menu__block__title">
        <span>
        {{ product.name }}
        </span>
    </div>
    <div class="menu__block__price">
        <span>
            {{ product.price }} &#x20BD;
        </span>
    </div>
    </div>
</div>

templates/main/blocks/page_header.html
<div class="page_header__container">
    <span>
        Меню
    </span>
</div>

templates/main/blocks/popup_form.html
<div class="pform__wrap"
id="main__popup">
    <div class="ppform__wrapper">
        <div class="pp__container">
            <i class="fa fa-check-circle pp__icon"></i>
            <div class="pp__message">
                Заявка принята
            </div>
            <div class="pp__message__body">
                В ближайшее время с вами свяжется менеджер!
            </div>
        </div>
    
    <div class="pform__container">
        <div class="pform__container__title">
            Обратный звонок
        </div>
        <div class="pform__container__subtitle">
            Оставьте номер телефона, и мы свяжемся с вами!
        </div>

        
        
        <div class="pform__container__form">
            <div class="input__empty__error">
                <span>
                    *Введите ваш номер телефона
                </span>
            </div>
            <input type="text"
            name="phone" id="input_phone"
            class="contact__input"
            placeholder="Телефон*"
            autocomplete="off">
            <span class="pform__button"
            id="pform_button">
            Заказать звонок
            </span>
        </div>
    </div>

    </div>

    <div class="pform__wrap__close">
        <i class="gg-close"></i>
    </div>
</div>

<div class="pform__wrap__wrapper">

</div>


<script>

$("#pform_button").click(function() {
  $(".input__empty__error").removeClass("show")
  var phone = $("#input_phone").val() 
  console.log(phone.length)
  if (phone.length == 0) {
      console.log('вы ничего не ввели')
      $(".input__empty__error").addClass("show")
  } else {

    $.ajax({
        url: "{% url 'main:contact_form' %}",
        data: {
            'phone': phone
        },
        success: function(response) {
            $(".pform__container").addClass('hide')
            $(".pp__container").addClass('show')
            setTimeout(function() {
                closeModal()
            }, 4000)
        }
    }) 

    
    
}
})

</script>

templates/main/blocks/projects_container.html
<div id="projects_anchor"></div>

<div class="projects__main__wrapper">

<div class="nice_title center blue">
    <span>
    Проекты
    </span>
</div>

<div class="projects_list">
    <div class="project">
        <div class="project__image">
            <img src="https://www.navyblueyachting.com/wp-content/uploads/2019/03/HVARPO.jpg" alt="">
        </div>
        <div class="project__title">
            <span>
                Название asdf asd fasdf sdf as f asdfasdf
            </span>
        </div>
    </div>
    <div class="project">
        <div class="project__image">
            <img src="https://www.navyblueyachting.com/wp-content/uploads/2019/03/HVARPO.jpg" alt="">
        </div>
        <div class="project__title">
            <span>
                Название
            </span>
        </div>
    </div>
    <div class="project">
        <div class="project__image">
            <img src="https://www.navyblueyachting.com/wp-content/uploads/2019/03/HVARPO.jpg" alt="">
        </div>
        <div class="project__title">
            <span>
                Название
            </span>
        </div>
    </div>
    <div class="project">
        <div class="project__image">
            <img src="https://www.navyblueyachting.com/wp-content/uploads/2019/03/HVARPO.jpg" alt="">
        </div>
        <div class="project__title">
            <span>
                Название
            </span>
        </div>
    </div>
    <div class="project">
        <div class="project__image">
            <img src="https://www.navyblueyachting.com/wp-content/uploads/2019/03/HVARPO.jpg" alt="">
        </div>
        <div class="project__title">
            <span>
                Название
            </span>
        </div>
    </div>
</div>

</div>

templates/main/blocks/services.html
<div id="services_anchor"></div>
<div class="services__wrapper">

    <div class="regular_title">
        <span>
            Наши услуги
        </span>
    </div>

<div class="service__list">


    <a class="service"
    href="">    
        <div class="service__title">
            Фуршет
        </div>
    </a>
    <a class="service"
    href="">    
        <div class="service__title">
            Банкет
        </div>
    </a>
    <a class="service"
    href="">    
        <div class="service__title">
            Кофе брейк
        </div>
    </a>
    <a class="service"
    href="">    
        <div class="service__title">
            Организация и проведение
        </div>
    </a>
    <a class="service"
    href="">    
        <div class="service__title">
            Обеспечение предприятий
        </div>
    </a>
    <a class="service"
    href="">    
        <div class="service__title">
            Аренда оборудования
        </div>
    </a>


    </div>

</div>

templates/main/includes_css.html
{% load static %}

<link rel="stylesheet" href="{% static 'plugins/magnific-popup.css' %}">
<link href='https://css.gg/css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'slick/slick.css'%}">
    <link rel="stylesheet" href="{% static 'slick/slick-theme.css'%}">
    <link rel="stylesheet" href="{% static 'js/owlcarousel/owl.carousel.css'%}">
    <link rel="stylesheet" href="{% static 'js/owlcarousel/owl.theme.default.css'%}">

    <link rel="stylesheet" href="{% static 'plugins/selectize/selectize.bootstrap4.css'%}">
    

templates/main/includes_js.html
{% load static %}

<script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
    

    <script src="{% static 'plugins/jquery.magnific-popup.js' %}"></script>

    <script src="{% static 'js/wayp/noframework.waypoints.min.js' %}"></script>
    <script src="{% static 'js/wayp/sticky.min.js' %}"></script>

    <script src="https://kit.fontawesome.com/bca16a3855.js" crossorigin="anonymous"></script>


    <script src="{% static 'slick/slick.js' %}"></script>

    <script src="{% static 'js/owlcarousel/owl.carousel.js' %}"></script>

    <script src="{% static 'plugins/selectize/selectize.js' %}"></script>

    <script src="{% static 'plugins/el-pagination/el-pagination.js' %}"></script>

    <script src="{% static 'js/particles.js' %}"></script>


    <script>
        /* particlesJS.load(@dom-id, @path-json, @callback (optional)); */
        particlesJS.load('particles-js', "{% static 'js/particles.json' %}", function() {
          console.log('callback - particles.js config loaded');
        });
        </script>

templates/main/index.html
{% extends './base.html' %}

{% block content %}
    
    {% include './blocks/intro_container.html' %}

    {% include './blocks/adv_container.html' %}

    {% include './blocks/services.html' %}

    <!-- {% include './blocks/projects_container.html' %} -->
    
    

    {% include './blocks/menu_block.html' %}



    {% include './blocks/about_us.html' %}

    {% include './blocks/action_call.html' %}

    {% include './blocks/contacts_container.html' %}

    

{% endblock content %}

templates/main/products.html
{% extends './base.html' %}

{% block content %}

    {% include './blocks/page_header.html' %}

    <div class="products__list">
        {% for product in products  %}
        {% include './blocks/menu_single.html' %}
        {% endfor %}
    </div>


    {% include './blocks/action_call.html' %}
    
{% endblock content %}